backend/controllers/TasksController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\project\Project;
use common\models\status\Status;
use common\models\task\Task;
use common\models\user_team_group\UserTeamGroup;
use common\models\users_profile\UsersProfile;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * TasksController implements the CRUD actions for Task model.
 */
class TasksController extends BaseController
{
    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Task::find(),
        ]);
        $profile = (new UsersProfile())->getProfile();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'profile' => $profile,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (Yii::$app->user->can('readTask')) {
            $profile = (new UsersProfile())->getProfile();

            return $this->render('view', [
                'model' => $this->findModel($id),
                'profile' => $profile,
            ]);
        }

        return new ForbiddenHttpException(Yii::t('app', 'This resouce forbidden for you.'));
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->can('createTask')) {
            $model = new Task();
            $projects = (new Project())->getProjectsArray();
            $teamleads = (new UserTeamGroup)->getTeamleadsArray();
            $assignees = (new UserTeamGroup)->getAssigneesArray();
            $statuses = (new Status)->getStatusesArray();
            $profile = (new UsersProfile())->getProfile();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('create', [
                'model' => $model,
                'projects' => $projects,
                'teamleads' => $teamleads,
                'assignees' => $assignees,
                'statuses' => $statuses,
                'profile' => $profile,
            ]);
        }

        return new ForbiddenHttpException(Yii::t('app', 'This resouce forbidden for you.'));
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->can('updateProject')) {
            $model = $this->findModel($id);
            $profile = (new UsersProfile())->getProfile();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('update', [
                'model' => $model,
                'profile' => $profile,
            ]);
        }

        return new ForbiddenHttpException(Yii::t('app', 'This resouce forbidden for you.'));
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->can('deleteProject')) {
            $this->findModel($id)->delete();

            return $this->redirect(['index']);
        }

        return new ForbiddenHttpException(Yii::t('app', 'This resouce forbidden for you.'));
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/TasksController.php
<?php

namespace frontend\controllers;

use \Yii;
use common\models\task\Task;
use common\models\task\TaskQuery;
use common\models\task\TaskSearch;
use yii\web\NotFoundHttpException;
use frontend\models\comment\Comment;
use common\models\users_profile\UsersProfile;
use common\models\users_profile\UsersProfileQuery;

/**
 * TasksController - class handels Task model and views/tasks
 */
class TasksController extends \yii\web\Controller
{
    /**
     * List of all Task models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $profile = (new UsersProfile())->getProfile();

        return $this->render(
            'index',
            [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'profile' => $profile,
            ]
        );
    }

    /**
     * Displays calendar list of user`s tasks.
     *
     * @return string
     */
    public function actionCalendar()
    {
        // Get current ID of logined user
        $userId = Yii::$app->user->getId() ?: '1000';
        $profile = (new UsersProfile())->getProfile();

        // Fill array keyes with [1, .., date("t")].
        // date("t") - count of days in current month
        $calendar = array_fill_keys(range(1, date("t")), []);
        $model = new TaskQuery(Task::class);

        foreach ($model->getByCurrentMonth($userId)->all() as $task) {
            // Get current $task->date and create new DateTime object
            // $date->format("j") -- Day of the month: 1, 2, .., 31
            // Fill array $calender with $task objects
            $date = \DateTime::createFromFormat("Y-m-d H:i:s", $task->deadline);
            $calendar[$date->format("j")][] = $task;
        }

        return $this->render('calendar', \compact('calendar', 'profile'));
    }

    /**
     * Displays a single Task model.
     *
     * @param integer $id - ID
     *
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $profile = (new UsersProfile())->getProfile();

        return $this->render(
            'view',
            [
                'model' => $this->findModel($id),
                'profile' => $profile,
            ]
        );
    }

    /**
     * Function for add commant
     *
     * @return boolean|string
     */
    public function actionAddComment()
    {
        $profile = (new UsersProfile())->getProfile();
        $model = new Comment();
        $model->task_id = Yii::$app->request->get('task_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->task_id]);
        }

        return $this->render('add-comment', \compact('model', 'profile'));
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id - ID
     *
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/tasks/_comment_form.php
<?php

use Yii;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\comment\Comment */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="row">
    <div class="col-md-9">    
        <p><?= Yii::t('app', 'For comment fill out the following field:'); ?></p>    
        <div class="comment-form">

            <?php $form = ActiveForm::begin([
                'id' => 'comment-form',
                'fieldConfig' => [
                    'template' => 
                        "<div>{label}</div><br>
                        <div class=\"col-md-9\">{input}</div><br>
                        <div class=\"col-md-9\">{error}</div><br>",
                    'labelOptions' => ['class' => 'col-md-9 control-label'],
                ],
            ]); ?>

            <?= $form->field($model, 'body')->textarea(['autofocus' => true, 'rows' => 8]); ?>

            <?= Html::activeHiddenInput($model, 'status', ['status' => $model::STATUS_ACTIVE]); ?>

                    <br><br><br><br><br><br><br>
                    <div class="form-group">                    
                            <?= Html::submitButton(
                                'Submit',
                                [
                                    'class' => 'btn btn-primary',
                                    'name' => 'comment-button',
                                ]
                            ); ?>
                    </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/tasks/_profile.php
<?php

$this->params['profile']['fullName']
    =  $profile ? $profile->first_name . ' ' . $profile->last_name
        : 'Guest';

$this->params['profile']['image'] = $profile ? $profile->image : '10_man.jpg';
$this->params['profile']['spec'] = $profile ? $profile->specialization : 'Web developer';
$this->params['profile']['id'] = $profile ? $profile->id : 'Not set';

frontend/views/tasks/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\task\TaskSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'title'); ?>

    <?= $form->field($model, 'start'); ?>

    <?= $form->field($model, 'end'); ?>

    <?= $form->field($model, 'deadline'); ?>

    <?= $form->field($model, 'description'); ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']); ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']); ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/tasks/add-comment.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\task\Task */

$this->title = 'Add comment to task: ' . $model->task->title;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['/tasks']];
$this->params['breadcrumbs'][] = [
    'label' => $model->task->title,
    'url' => [
        'view',
        'id' => $model->task_id
    ],
];

echo $this->render('_profile', ['profile' => $profile]);
?>
<div class="tasks-comment">

    <h1><?= Html::encode($this->title); ?></h1>

    <?= $this->render(
        '_comment_form',
        [
            'model' => $model,
        ]
    ); ?>

</div>

frontend/views/tasks/calendar.php
<?php
/** @var array $calendar */
use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php echo $this->render('_profile', ['profile' => $profile]); ?>

<div>
    <?= Yii::t('app', 'Current date: {0, date, dd MMMM yyyy}', time()); ?>
</div>
<div class="table-responsive">
    <table class="table table-striped">   
        <tr>
            <td>
                <?= Yii::t('app', 'Date of month'); ?>
            </td>
            <td><?= Yii::t('app', 'Event'); ?></td>
            <td><?= Yii::t('app', 'Deadline'); ?></td>
            <td><?= Yii::t('app', 'Status'); ?></td>
            <td><?= Yii::t('app', 'Total events'); ?></td>
        </tr>
        <?php foreach ($calendar as $day => $events) : ?>
            <tr class="<?=(count($events) > 0)?'warning' : ''?>">
                <td class="td-date"><span class="label label-success"><?=$day;?></span></td>
                <td>
                    <?=(count($events) > 0) ?
                    '<p>'
                        . ucfirst($events[0]->title)
                    . '</p>'
                    .'<p class="small">' .
                        ucfirst($events[0]->description)
                    . '</p>'
                        : '-';
                    ?>
                </td>
                <td>
                <?= (count($events) > 0) ?
                '<p class="warning">' . Yii::$app->formatter->asDate($events[0]->deadline) . '</p>'
                    : '-';
                ?>
                </td>
                <td>
                    <?php if (count($events) > 0) : ?>
                    <p>
                        <?php echo ($events[0]->status == 10) ? 'Active' : 'Not active'; ?>
                    </p>
                    <?php else : ?>
                    <p> - </p>
                    <?php endif; ?>
                </td>
                <td class="td-event">
                    <?= (count($events) > 0) ? Html::a(
                        count($events),
                        Url::to(['tasks/view', 'id' => $events[0]->id])
                    ) : '-';
                    ?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
</div>

frontend/views/tasks/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models\task\TaskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tasks';
$this->params['breadcrumbs'][] = $this->title;

echo $this->render('_profile', ['profile' => $profile]);
?>
<div class="task-index">

    <h1><?=Html::encode($this->title);?></h1>
    <div class="row">
        <div class="col-md-6">
            <?php // echo $this->render('_search', ['model' => $searchModel]);?>
        </div>
    </div>

    <?= GridView::widget(
        [
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id',
                'title:text',
                'start:date',
                'deadline:date',
                'end:date',
                'description:ntext',
                'assignee_id',
                'teamlead_id',
                [
                    'label' => 'Status',
                    'content' => function ($model, $key, $index, $column) {
                          return $model->getStatus();
                    },
                    'format' => 'text',
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => 'Actions',
                    'template' => '{view}{add-comment}',
                    'buttons' => [
                        'add-comment' => function ($url, $model, $key) {
                            return Html::a(
                                '<span class="glyphicon glyphicon-book"></span>',
                                [
                                    'add-comment',
                                    'task_id' => $model->id,
                                ]
                            );
                        },
                    ],
                    'visibleButtons' => [
                        'view' => \Yii::$app->user->can('readTask'),
                        'add-comment' => \Yii::$app->user->can('readTask'),
                    ],
                ],
            ],
        ]
    ); ?>
</div>

frontend/views/tasks/view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\tables\Task */

$this->title = $model->title;
$this->params['breadcrumbs'][]
    = ['label' => Yii::t('app', 'Tasks'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

echo $this->render('_profile', ['profile' => $profile]);
?>
<div class="task-view">

    <?=DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'assignee_id',
            'teamlead_id',
            'start',
            'end',
            'deadline',
            'description:html',
            'status',
        ],
    ]);?>

    <div class="row">
        <div class="col-lg-8">
            <button class="btn btn-lg btn-primary">
                <?=Html::a(
                    Yii::t('app', 'Add comment'),
                    Url::to(['add-comment', 'task_id' => $model->id]),
                    ['class' => 'link-white']
                );?>
            </button>
        </div>
    </div>
</div> 